### ISSUE TITLE
Correctly using Vue with Parcel

### ISSUE THREAD

**Issue by locness3** [Scratch-Client-4/itchy-cordova#11]
Currently, Vue is being in the project's code and being imported without using Parcel. This is bad practice (i think? lmao). We should switch to "the correct way", as [this video](https://www.youtube.com/watch?v=4deVCNJq3qc)'s part 2 will teach you better than me. While we're doing that, we should split stuff over multiple, reusable components and make more use of Vue's features (like using its data store instead of plain old JS variables, which has the non-negligible advantage of making things react to the changes)

**Comment by micahlt** [comment]
I tried including Vue without the direct file and I get a whole string of issues.  File a pull if you can fix it!   :D

**Comment by locness3** [comment]
I also got issues using Vue and Parcel trying to do some work on teh desktop version.

**Comment by locness3** [comment]
Might not be Parcel-related tho.

**Comment by micahlt** [comment]
@locness3 True... I'm also having some issues with Ionic installations via `npm`, so who knows.

**Comment by locness3** [comment]
One issue I've had with Vue+Parcel, is that by default, it includes a "runtime-only" build of Vue, wich doesn't parse templates inside of HTML 😒

**Comment by locness3** [comment]
(and I still didn't fix it lol)

**Comment by micahlt** [comment]
@locness3 Yeah, that's the main problem I'm having.

**Comment by AyzansAlt** [comment]
poopi

**Comment by locness3** [comment]
In my "refactoring" that I was doing before the new redesign, I was "fixing" this and I found out that using Vue with a bundler works quite differently. I recommend watching the part 2 of [this video](https://www.youtube.com/watch?v=4deVCNJq3qc) so you can get an understanding of using Vue with a bundler (in the video, it's vue-cli/webpack but the same works with Parcel).

@micahlt @Scratch-Client-4/frontend

**Comment by micahlt** [comment]
Not sure if you're aware of this yet, but the current status is that we're not actually using Vue in the rebuild of SC4 (Itchy).  We _could_ technically re-implement it, but we need to consider performance: is Vue actually needed in the first place?

**Comment by locness3** [comment]
I'm not aware, nice collaboration 👌

**Comment by locness3** [comment]
It's not really needed but it really simplifies development when you get used to it and properly use its features

**Comment by micahlt** [comment]
So would you be willing to re-implement it in SC4M. I'm really busy this week and probably won't have time to make a single commit...

**Comment by locness3** [comment]
I would!

**Comment by micahlt** [comment]
If you think it's necessary, of course.  I for one enjoy vanilla JS, but if this will improve our development speed and productivity then go for it!  🤠

**Comment by locness3** [comment]
If we use Vue, we should also use this https://www.npmjs.com/package/vue-material-design-icons, btw.

**Comment by micahlt** [comment]
I'll just come out and say that I would be completely fine avoiding Vue - I really don't like frameworks.  They just make the app larger and then you have to take the time to learn a whole new approach.  We've got a good project rendering function right now, and that's what we would probably use Vue for the most.

**Comment by locness3** [comment]
I personnally think it's better to use frameworks because :
- You can split stuff into distinct, reusable components which improves maintainability and flexibility
- All the "reactive" stuff - once you have your template written, just change some variables to change its content - without chaining multiple `textContent`s.

If we choose to go no-frameworks, we should get to know librairies and stuff for making the code cleaner and easier to maintain (especially for this kind of projects which can get really huge)

**Comment by locness3** [comment]
> If we choose to go no-frameworks, we should get to know librairies and stuff for making the code cleaner and easier to maintain (especially for this kind of projects which can get really huge)

~~and i'll go make my own app~~

**Comment by locness3** [comment]
why

**Comment by micahlt** [comment]
@locness3 Didn't we establish that we're just using modularized JS instead of a framework?

**Comment by locness3** [comment]
ye
