### ISSUE TITLE
Viewing projects

### ISSUE THREAD

**Issue by locness3** [Scratch-Client-4/itchy-cordova#25]
Add the ability to view projects (using forkphorus, I'd include its code directly in our thing with a git submodule) and their details and comments. We should also make it so that the projects don't load instantly, the worst thing with scratch's mobile website. Instead, the user would do some kind of interaction before the project loads.

**Comment by AyzansAlt** [comment]
but, but that was my question :( #24

**Comment by locness3** [comment]
I just rephrased it ;)

**Comment by YOYITsM3M8** [comment]
> using forkphorus

Nonono use turbowarp.org

**Comment by locness3** [comment]
Maybe? I'm not sure which one's better

**Comment by YOYITsM3M8** [comment]
Fork was made by the same person as turbo turbo is better they said

**Comment by locness3** [comment]
we'll see

**Comment by micahlt** [comment]
@YOYITsM3M8 Currently Forkphorus has better embed options than TurboWarp.

**Comment by YOYITsM3M8** [comment]
> @YOYITsM3M8 Currently Forkphorus has better embed options than TurboWarp.

Okay, but I would still recommend turbowarp

**Comment by AyzansAlt** [comment]
***forking turbowarp for itchy, externally named "Xenon", Internally Named "idk help"***

**Comment by locness3** [comment]
:thinking:

**Comment by micahlt** [comment]
@AyzansAlt It's not relevant - we won't ship a full TurboWarp engine with the app, that'll make it huge.

**Comment by locness3** [comment]
I'd argue that embedding TurboWrap would still have it be downloaded to the user's device

**Comment by AyzansAlt** [comment]
Externally?

**Comment by locness3** [comment]
Would still take storage space (at least cache)

Also I think we'll use forkphorus

**Comment by micahlt** [comment]
@locness3 Honestly, now that I'm investigating, TurboWarp actually is a lot better.  It handles graphics a lot better than both Forkphorus and Scratch itself, and its 60FPS feature would be nice to have.  TurboWarp also isn't that big of a download.  Forkphorus is kinda going out of support now that @GarboMuffin has started building on TurboWarp.

**Comment by locness3** [comment]
Okay, we'll use turbowarp

**Comment by micahlt** [comment]
@locness3 It would be possible to embed Turbowarp without a ton of space.  The engine takes up <13MB, so it's not significant.

**Comment by locness3** [comment]
k

**Comment by AyzansAlt** [comment]
> @locness3 Honestly, now that I'm investigating, TurboWarp actually is a lot better. It handles graphics a lot better than both Forkphorus and Scratch itself, and its 60FPS feature would be nice to have. TurboWarp also isn't that big of a download. Forkphorus is kinda going out of support now that @GarboMuffin has started building on TurboWarp.

umm what did I say

**Comment by micahlt** [comment]
@locness3 Can you work on adding TurboWarp in as a submodule?

**Comment by locness3** [comment]
```bash
git submodule init
# for each repo
git submodule add https://github.com/owner/repo

git commit -m "whatever"
git push
```

**Comment by micahlt** [comment]
Huh, okay.  But then how do we use the code?  I'll have to read up on
submodules; I'm not familiar with them.

**Comment by micahlt** [comment]
This was partially finished in PR #35.

**Comment by micahlt** [comment]
@locness3 Could I close this?
